version: "1"

# one for each dockerfile we are managing
services:
  api:
    build: .
    platform: linux/arm64 # required to run on  GCP
    ports:
      - 8080:8080
    environment:
      LOCAL: "true"
      PORT: 8080
      REDIS_URL: redis
    depends_on: # required for local instance of redis
      - redis
  redis:
    build: db
    platform: linux/arm64 # required to run on  GCP
    ports:
      - "6379:6379"
    volumes:
      - .data:/data
